### ISSUE TITLE
Error in categories.csv entry orders

### ISSUE THREAD

**Issue by Flxlisboa** [commercetools/commercetools-sunrise-data#121]
I believe there is an error on this file, as the categories fail to upload into a project. Suspect record c154 (**sale-men**) needs to be fit between **c151** and **c152** for the category creation to be completed successfully.

**Comment by plaskevich** [comment]
I think this error may be caused by node version. I guess you are using version 11, please install version 9 and try again. Sunrise data is not yet fully compatible with the latest node and it may throw some errors.

**Comment by Hegi** [comment]
I'm experiencing the same issue and I am using `node v9.9.0` and `npm 5.6.0`. Here is the error log:

```> sunrise@1.0.0 import:categories C:\Work\commercetools-sunrise-data
> cross-env-shell "node_modules/.bin/category-sync import -f data/categories.csv -p $npm_package_config_projectKey --clientId $npm_package_config_clientId  --clientSecret $npm_package_config_clientSecret"

{"name":"sphere-category-sync-1.2.0","hostname":"****","pid":6280,"level":50,"data":{"body":{"statusCode":401,"message":"Please provide valid client credentials using HTTP Basic Authentication.","errors":[{"code":"invalid_client","message":"Please provide valid client credentials using HTTP Basic Authentication."}],"error":"invalid_client","error_description":"Please provide valid client credentials using HTTP Basic Authentication.","originalRequest":{"endpoint":"/categories?where=externalId%20in%20(%221%22)&sort=id%20asc","options":{"config":{"project_key":"****"},"host":"api.sphere.io","protocol":"https","timeout":20000,"rejectUnauthorized":true,"headers":{"User-Agent":"sphere-node-sdk"},"uri":"https://api.sphere.io/****","gzipEnable":true}}},"message":"Please provide valid client credentials using HTTP Basic Authentication.","name":"Unauthorized","stack":"Unauthorized: Please provide valid client credentials using HTTP Basic Authentication.","code":401,"statusCode":401},"project_key":"****","msg":"undefined","time":"2019-05-27T18:55:19.047Z","v":0}
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\.bin\category-sync import -f data\categories.csv -p %npm_package_config_projectKey% --clientId %npm_package_config_clientId%  --clientSecret %npm_package_config_clientSecret% ENOENT
    at notFoundError (D:\Work\commercetools-sunrise-data\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (D:\Work\commercetools-sunrise-data\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (D:\Work\commercetools-sunrise-data\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
Emitted 'error' event at:
    at ChildProcess.cp.emit (D:\Work\commercetools-sunrise-data\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sunrise@1.0.0 import:categories: `cross-env-shell "node_modules/.bin/category-sync import -f data/categories.csv -p $npm_package_config_projectKey --clientId $npm_package_config_clientId  --clientSecret $npm_package_config_clientSecret"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sunrise@1.0.0 import:categories script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     %APPDATA%\npm-cache\_logs\2019-05-27T18_55_19_085Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sunrise@1.0.0 start: `npm run clean:data && npm run import:types && npm run import:channels && npm run import:taxCategories && npm run import:zones && npm run import:projectSetup && npm run import:shippingmethods && npm run import:customers && npm run import:categories && npm run sync:products && npm run import:orders`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sunrise@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     %APPDATA%\npm-cache\_logs\2019-05-27T18_55_19_145Z-debug.log
```

**Comment by harm-meijer** [comment]
The new release will insert parent categories first, no matter what order they are in the csv.
