### ISSUE TITLE
Error: Couldn't find preset "stage-0" relative to directory 

### ISSUE THREAD

**Issue by okkevdeijk** [commercetools/commercetools-sunrise-data#124]
Hi guys,

I'm running into an issue while trying to import the sunrise-data into a newly made Commercetools project. The following error occurs:

```
./node_modules/sphere-category-sync/node_modules/bluebird/js/main/thenables.js -> dist\node_modules\sphere-category-sync\node_modules\bluebird\js\main\thenables.js
./node_modules/sphere-category-sync/node_modules/bluebird/js/main/timers.js -> dist\node_modules\sphere-category-sync\node_modules\bluebird\js\main\timers.js
./node_modules/sphere-category-sync/node_modules/bluebird/js/main/using.js -> dist\node_modules\sphere-category-sync\node_modules\bluebird\js\main\using.js
./node_modules/sphere-category-sync/node_modules/bluebird/js/main/util.js -> dist\node_modules\sphere-category-sync\node_modules\bluebird\js\main\util.js
Error: Couldn't find preset "stage-0" relative to directory "C:\\Source\\Commercetools\\commercetools-sunrise-data\\node_modules\\sphere-customer-import"
    at C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-cli\lib\babel\util.js:50:22)
npm ERR! code ELIFECYCLE
```

I tried several solutions according to what I found on Google, but that doesn't help. Is there someone who could suggest what I can do and help me out? 

Working on a Windows 10 machine, Java en Maven installed.

**Comment by Jonne** [comment]
Same issue here, also on windows

**Comment by plaskevich** [comment]
Hi, could you please tell me the node version that you are using?

**Comment by Jonne** [comment]
I've tried 6.10.3 & 8.9.1

**Comment by okkevdeijk** [comment]
I am currently using v8.16.0, and also tried with the latest version 9

**Comment by plaskevich** [comment]
what solutions did you try? did you try adding `babel-preset-stage-0`?

https://github.com/webpack/webpack/issues/2785#issuecomment-360605994

**Comment by okkevdeijk** [comment]
I tried babel-preset-stage-0, but running into a similar issue again:

```
Error: Couldn't find preset "@babel/preset-env" relative to directory "C:\\Source\\Commercetools\\commercetools-sunrise-data\\node_modules\\sphere-node-utils\\node_modules\\csv-generate"
    at C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\Source\Commercetools\commercetools-sunrise-data\node_modules\babel-cli\lib\babel\util.js:50:22)
npm ERR! code ELIFECYCLE
```

**Comment by plaskevich** [comment]
what script exactly are you running? does it build successfully with `npm run build`?

**Comment by DBFBlackbull** [comment]
Hey, I have a similar problem. I use the following versions:
- npm v5.6.0
- Node v8.11.1
- Java v1.8.0_212

I also had to install Python as I got a message for "comlet python was not found", even though it isn't on the list of required software
- Python v2.7.16

I also installed some C++ redistributables as I got an error for a .NET Framework 2.0 VCBuild.exe that it couldn't find.

Also installed Maven as it was also required, but not on the list:
- mvn: 3.6.1

After all this, when I do a clean pull from github and does a 'npm install' I get the following error:
```
PS D:\git\commercetools-sunrise-data> npm install

> dtrace-provider@0.8.7 install D:\git\commercetools-sunrise-data\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js


D:\git\commercetools-sunrise-data\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Users\PBM\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\PBM\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at _errnoException (util.js:1022:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PBM\\AppData\\Roaming\\nvm\\v8.11.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\git\commercetools-sunrise-data\node_modules\dtrace-provider
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1399 packages in 16.215s
PS D:\git\commercetools-sunrise-data>
```

If I ignore that and continue onwards to setting all the project credentials and then running 'npm run start' then I get the same error as described above:
```
./node_modules/sphere-category-sync/node_modules/bluebird/js/main/util.js -> dist\node_modules\sphere-category-sync\node_modules\bluebird\js\main\util.js
Error: Couldn't find preset "stage-0" relative to directory "D:\\git\\commercetools-sunrise-data\\node_modules\\sphere-customer-import"
    at D:\git\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (D:\git\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (D:\git\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\git\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (D:\git\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\git\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\git\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\git\commercetools-sunrise-data\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (D:\git\commercetools-sunrise-data\node_modules\babel-cli\lib\babel\util.js:50:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sunrise@1.0.0 build: `rimraf dist/ && babel ./**/*.js --out-dir dist/ --ignore ./node_modules,./.babelrc,./package.json,./npm-debug.log --copy-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sunrise@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PBM\AppData\Roaming\npm-cache\_logs\2019-05-22T11_11_20_494Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sunrise@1.0.0 preclean:categories: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sunrise@1.0.0 preclean:categories script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PBM\AppData\Roaming\npm-cache\_logs\2019-05-22T11_11_20_517Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sunrise@1.0.0 clean:data: `npm run clean:categories && npm run clean:products && npm run clean:inventory && npm run clean:orders && npm run clean:carts && npm run clean:states && npm run clean:customers && npm run clean:shippingmethods && npm run clean:zones && npm run clean:taxCategories && npm run clean:channels && npm run clean:types`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sunrise@1.0.0 clean:data script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PBM\AppData\Roaming\npm-cache\_logs\2019-05-22T11_11_20_541Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sunrise@1.0.0 start: `mvn clean && npm run clean:data && npm run import:types && npm run import:channels && npm run import:taxCategories && npm run import:zones && npm run import:projectSetup && npm run import:shippingmethods && npm run import:customers && npm run import:categories && npm run sync:products && npm run import:orders`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sunrise@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PBM\AppData\Roaming\npm-cache\_logs\2019-05-22T11_11_20_565Z-debug.log
```

Here is the log files
[2019-05-22T11_11_20_565Z-debug.log](https://github.com/commercetools/commercetools-sunrise-data/files/3207081/2019-05-22T11_11_20_565Z-debug.log)
[2019-05-22T11_11_20_541Z-debug.log](https://github.com/commercetools/commercetools-sunrise-data/files/3207082/2019-05-22T11_11_20_541Z-debug.log)
[2019-05-22T11_11_20_517Z-debug.log](https://github.com/commercetools/commercetools-sunrise-data/files/3207083/2019-05-22T11_11_20_517Z-debug.log)
[2019-05-22T11_11_20_494Z-debug.log](https://github.com/commercetools/commercetools-sunrise-data/files/3207084/2019-05-22T11_11_20_494Z-debug.log)
