### ISSUE TITLE
Error: Cannot find module 'config-chain'

### ISSUE THREAD

**Issue by jspadhi** [commercetools/commercetools-sunrise-data#125]
Error: Cannot find module 'config-chain'

D:\SunriseStore\commercetools-sunrise-data>npm run start

> sunrise@1.0.0 start D:\SunriseStore\commercetools-sunrise-data
> mvn clean && npm run clean:data && npm run import:types && npm run import:channels && npm run import:taxCategories && npm run import:zones && npm run import:projectSetup && npm run import:shippingmethods && npm run import:customers && npm run import:categories && npm run sync:products && npm run import:orders

[INFO] Scanning for projects...
[INFO]
[INFO] --< com.commercetools.demo.data.import:commercetools-demo-data-import >--
[INFO] Building commercetools-demo-data-import 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ commercetools-demo-data-import ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.432 s
[INFO] Finished at: 2019-05-20T18:44:04+05:30
[INFO] ------------------------------------------------------------------------
module.js:549
    throw err;
    ^

Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\SunriseStore\commercetools-sunrise-data\node_modules\npm\lib\config\core.js:1:72)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sunrise@1.0.0 start: `mvn clean && npm run clean:data && npm run import:types && npm run import:channels && npm run import:taxCategories && npm run import:zones && npm run import:projectSetup && npm run import:shippingmethods && npm run import:customers && npm run import:categories && npm run sync:products && npm run import:orders`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sunrise@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jyoti88262\AppData\Roaming\npm-cache\_logs\2019-05-20T13_14_05_253Z-debug.log

**Comment by jspadhi** [comment]
Logs: 
[2019-05-20T13_14_05_253Z-debug.log](https://github.com/commercetools/commercetools-sunrise-data/files/3198081/2019-05-20T13_14_05_253Z-debug.log)
