### ISSUE TITLE
unhandled exception in orders import

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-sunrise-data#144]
Getting this error when importing into a clean empty project using the current master: 

```
(node:83096) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'errors' of undefined
    at _services.client.execute.catch.err (/Users/nkuehn/GitHub/commercetools-sunrise-data/dist/lib/orders.js:93:75)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by michaelashe** [comment]
I can back up @nkuehn here as I came across the exact same error message as I was testing another issue.

**Comment by harm-meijer** [comment]
Do you still get this error with the new release?
