### ISSUE TITLE
error reading env variables

### ISSUE THREAD

**Issue by rmrcorp** [commercetools/commercetools-sunrise-data#187]
I have cloned the "commercetools-sunrise-data" proyect and I created the project "name-1" and I dowloaded the .evn data as "env.name-1" file. The file was copied at the project root folder.
When I execute the "npm run start" this message appears....
`
> sunrise@1.0.0 start
> npm run build && node dist/lib/data.js --start

> sunrise@1.0.0 build
> rimraf dist/ && babel ./lib/*.js --out-dir dist/lib/ --ignore ./node_modules,./.babelrc,./package.json,./npm-debug.log --copy-files

Successfully compiled 22 files with Babel (941ms).
--------------------------------------------------------
projectKey: undefined
clientId: undefined
clientSecret: undefined
authUrl: https://undefined
apiUrl: https://undefined
--------------------------------------------------------
/Users/ruben.marin/proyects/commercetools/data/commercetools-sunrise-data/node_modules/@commercetools/api-request-builder/dist/api-request-builder.cjs.js:1164
  if (!projectKey) throw new Error('No project defined. Please enter a project key');
                   ^

Error: No project defined. Please enter a project key
    at createService (/Users/ruben.marin/proyects/commercetools/data/commercetools-sunrise-data/node_modules/@commercetools/api-request-builder/dist/api-request-builder.cjs.js:1164:26)
    at /Users/ruben.marin/proyects/commercetools/data/commercetools-sunrise-data/node_modules/@commercetools/api-request-builder/dist/api-request-builder.cjs.js:1236:81
    at Array.reduce (<anonymous>)
    at createRequestBuilder (/Users/ruben.marin/proyects/commercetools/data/commercetools-sunrise-data/node_modules/@commercetools/api-request-builder/dist/api-request-builder.cjs.js:1235:35)
    at createProjectService (/Users/ruben.marin/proyects/commercetools/data/commercetools-sunrise-data/dist/lib/services.js:38:80)
    at Object.<anonymous> (/Users/ruben.marin/proyects/commercetools/data/commercetools-sunrise-data/dist/lib/services.js:117:24)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
`

I don't know why it's happening

**Comment by rmrcorp** [comment]
sorry, I close the issue because the problem was at the file name, must be ".env"
